#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := sdmmcplayer

EXTRA_COMPONENT_DIRS += ../../ESP32AudioLibrary
include $(IDF_PATH)/make/project.mk

