#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := a2dpinput

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../
EXTRA_COMPONENT_DIRS += ../../ESP32AudioLibrary
include $(IDF_PATH)/make/project.mk

